Fetch Time for 10 is 12.779417
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.765167
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.953132
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a160>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.59441
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.086068
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bdc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.431554
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366770fee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.395696
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677023d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 10.291193
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 11.230364
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706220>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 4.951787
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769af70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677063a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.402352
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.102141
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702700>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769af70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.951497
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677066a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 10.64689
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 4.268788
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677069d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769af70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.38511
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.956777
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ba60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.327467
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677066a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 21.581949
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.939737
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677066a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 18.236622
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.686441
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769af40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 10.015433
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a700>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.662662
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.869612
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677065e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 10.072009
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769af10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677069d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 13.258297
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769adc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 18.572332
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 20.409128
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702370>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677063a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 11.480381
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769baf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677028b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.149213
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 13.895309
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677063a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.966007
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677068b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.27187
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769adf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.593536
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366790cbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.738225
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.599926
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b0a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677064f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 4.226386
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769acd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.066139
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.897073
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a160>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 4.709014
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677062b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.310216
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769afd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677027f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.46365
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769adf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366770fe80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.996024
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.826562
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.644724
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769adf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.193167
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aa60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.403617
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677024c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.839584
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769af40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769beb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702700>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.295363
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.479321
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 4.616018
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ac10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677066a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.609189
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bc70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.531189
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ab20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.351554
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.479404
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bb20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.585513
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ab50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.284557
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677023d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769abe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.707409
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677021c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677067c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.840799
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a640>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677024c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.011953
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769beb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.657826
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769baf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.128341
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bdc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.033648
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b970>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.985274
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677023d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ab50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.391032
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769abe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.633621
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677061c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.031247
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ae50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366770f5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.858577
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769beb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ac10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.515429
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.511612
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.928006
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.210872
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bfa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aa60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.446448
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677066a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.765987
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.305015
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aa60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.129861
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ac70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 11.416407
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bd30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.186482
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.298493
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769af10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 11.963154
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 13.674739
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 10.613046
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769af10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 10.133675
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aa00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.490698
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.037683
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.072496
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aa00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bbb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.622943
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ae20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.917039
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ba60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ae80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.920246
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.228092
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366770f8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.413179
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.126468
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ad00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 11.189429
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 13.116348
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769adc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366770f250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.115957
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.468065
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702310>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769baf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 12.15376
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.751913
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706340>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677022e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 11.138582
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677065b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.060978
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366770fca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 11.596424
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 10.115269
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.86282
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ae80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702580>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.636665
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a910>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 4.75195
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.539027
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b670>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.963765
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.434992
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.587086
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677020a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aa90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.7663
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677027f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.761745
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677068b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.103319
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769baf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 4.57768
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677023a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.546419
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ba60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.780203
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.595729
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.681335
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 11.505074
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.249859
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bb80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677066a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 11.357153
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ae50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 8.898418
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677063d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.307082
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706100>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bb80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 12.017098
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ad00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.539372
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677027f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677061c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.047733
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a790>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 14.790437
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702730>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677066d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.683378
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a760>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 10.506078
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706160>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ac70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 10.256678
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b610>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.353654
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702850>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bf40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706160>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.488121
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b550>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677021c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 14.886064
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706460>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a250>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.489464
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.501052
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769beb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 12.967622
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bdc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677027f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.906958
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677068b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 4.211143
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769ba60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a940>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 10.34198
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b3a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.30866
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702490>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677065b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 12.946643
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aaf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769beb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 9.113663
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677063a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677061f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a880>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.230661
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b220>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 11.513631
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769aee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677061c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 11.542024
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769afd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.260414
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702130>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a160>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.636982
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677065e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 5.93752
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.423698
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769bee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769afd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b520>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 6.121292
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667706fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702430>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769a5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Fetch Time for 10 is 7.769756
Exception called for cameraid 10 and usecase_id 7 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3667702280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 9 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f366769b3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Exception called for cameraid 10 and usecase_id 6 exception HTTPConnectionPool(host='172.16.0.178', port=8007): Max retries exceeded with url: /postprocess (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36677067c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
